apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vulnmap-ls
  annotations:
    github.com/project-slug: khulnasoft-lab/vulnmap-ls
    github.com/team-slug: vulnmap/hammerhead
spec:
  type: external-tooling
  lifecycle: "-"
  owner: hammerhead
