version: 2.1

orbs:
  prodsec: vulnmap/prodsec-orb@1.0

workflows:
  version: 2
  CICD:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - vulnmap-bot-slack
          channel: hammerhead-alerts
